### ISSUE TITLE
Root service request should not return error

### ISSUE THREAD

**Issue by databyte** [LightshedHealth/imagine#5]
When requesting just the root URL, you get the following error:

```
Error: Cannot find module 'ejs'
   at Function.Module._resolveFilename (module.js:339:15)
   at Function.Module._load (module.js:290:25)
   at Module.require (module.js:367:17)
   at require (internal/module.js:16:19)
   at new View (/src/node_modules/express/lib/view.js:78:30)
   at EventEmitter.render (/src/node_modules/express/lib/application.js:569:12)
   at ServerResponse.render (/src/node_modules/express/lib/response.js:961:7)
   at /src/app.js:25:7
   at Layer.handle_error (/src/node_modules/express/lib/router/layer.js:71:5)
   at trim_prefix (/src/node_modules/express/lib/router/index.js:310:13)
```

It should probably just return a 404.

**Comment by joedursun** [comment]
This was caused by a lack of a proper template engine. `ejs` was referenced but not installed (leftover cruft from my local experiments). I chose to go with [Pug](https://github.com/pugjs/pug) as it is simple, seems to be preferred in the Express community (for today at least 😉  ), and is clean like Ruby's Slim template engine.

[Fixed here](https://github.com/LightshedHealth/imagine/commit/c01b72b59af78acbaecd12b39da1bd65a085a048)
